server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myprojects
    username: root
    password: Raju@8465
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: paymentservice
